---
- name: Install Java for Jenkins
  ansible.builtin.apt:
    name:
      - fontconfig
      - openjdk-17-jre
    state: present
    update_cache: true

- name: Add Jenkins apt key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: "0644"
    force: true

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
    update_cache: true

- name: Enable and start Jenkins
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true
